### PR TITLE
Create scaffolding for note taking

### PR DESCRIPTION
**Pull request by acmiyaguchi**
Created a model with a few basic attributes necessary. Created the scaffolding for the model and added the route to be default root.

### CODE REVIEW

**Comment by DxTania** [comment]
One little nit: the body of a note should be "text" not "string" because strings can't be as long and should be used for short input (like I'm pretty sure title is ok as a string)

ref: http://stackoverflow.com/questions/3354330/difference-between-string-and-text-in-rails

**Comment by DxTania** [comment]
After some more research, apparently SQLite doesn't enforce limits on varchar like MySQL does, so I guess it doesn't matter

**Comment by DxTania** [comment]
We should probably all talk about what DB to use before we do anything else

**Comment by acmiyaguchi** [comment]
We don't necessarily need to choose a database now, I think ActiveRecord will use sqlite by default for development. We can choose and configure something more robust when we deploy.

**Comment by DxTania** [comment]
Yeah, I was just suggesting it for reasons like this (type stuff) but I'm guessing we won't have to change much anyways so sounds good to me!

**Comment by acmiyaguchi** [comment]
Thanks!

**Pull request merged**
